{
  "number": 5155,
  "title": "CallTarget can report MSB4132",
  "body": "```xml\r\n<Project>\r\n\r\n  <Target Name=\"Init\">\r\n    <CallTarget Targets=\"Inside\" />\r\n  </Target>\r\n\r\n  <Target Name=\"Inside\">\r\n    <Error />\r\n  </Target>\r\n\r\n</Project>\r\n```\r\n\r\n```sh-session\r\n$ msbuild -v:m\r\nMicrosoft (R) Build Engine version 16.6.0-preview-20126-02+13cfe7fc5 for .NET Framework\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nS:\\play\\calltarget-failure\\test.proj(8,5): error : (No message specified)\r\nS:\\play\\calltarget-failure\\test.proj(4,5): error MSB4132: The \"CallTarget\" task returned f\r\nalse but did not log an error.\r\n```\r\n\r\nThe second error here is redundant; `CallTarget` should be special-cased in the engine just like the `MSBuild` task is:\r\n\r\nhttps://github.com/microsoft/msbuild/blob/13cfe7fc5a97772e4045671c71fa31a3c0856af0/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs#L957-L959",
  "state": "CLOSED",
  "createdAt": "2020-03-03T20:50:36Z",
  "updatedAt": "2024-02-21T17:04:51Z",
  "closedAt": "2020-03-16T11:59:54Z",
  "author": {
    "login": "rainersigwald"
  },
  "labels": [
    "Area: Debuggability",
    "Area: Engine",
    "triaged"
  ],
  "assignees": {
    "nodes": []
  },
  "milestone": {
    "title": "MSBuild 16.6 Preview 2"
  },
  "comments": {
    "nodes": [
      {
        "body": "@BenVillalobos I penciled this in for p2 but it's a bugfix and can slip to 16.6 p3 without problems if we need to.",
        "createdAt": "2020-03-03T20:51:14Z",
        "updatedAt": "2020-03-03T20:51:14Z",
        "author": {
          "login": "rainersigwald"
        }
      },
      {
        "body": "Reopening for upstream #5173.",
        "createdAt": "2020-03-11T21:41:34Z",
        "updatedAt": "2020-03-11T21:41:34Z",
        "author": {
          "login": "rainersigwald"
        }
      }
    ]
  }
}