{
  "number": 10050,
  "title": "[NETSDKE2E]The error count displays incorrectly in output of dotnet test xunit.",
  "body": "### Issue Description\r\n\r\nBuild info:\r\n9.0.100-preview.4.24221.5\r\n\r\nThe error account displays incorrectly in output of dotnet test xunit.\r\n\r\n\r\n\r\n\r\n\r\n### Steps to Reproduce\r\n\r\nIn CLI: dotnet new xunit -o myxunit\r\nadd below codes\r\n```\r\nnamespace myxunit;\r\n\r\npublic class UnitTest1\r\n{\r\n    [Fact]\r\n    public void Test3()\r\n    {\r\n\r\n    }\r\n    [Fact]\r\n    public void Test1()\r\n    {\r\nAssert.Equal(12, 11);\r\n    }\r\n    [Fact]\r\n    public void Test2()\r\n    {\r\nAssert.Equal(11, 11);\r\n    }\r\n}\r\n```\r\ndotnet test\r\n\r\n### Expected Behavior\r\n\r\nThe log can be displayed well.\r\n\r\n### Actual Behavior\r\n\r\n\r\nThe log displays \"Build failed with 2 errors\", but error and error VSTEST1 for test 1 method should be considered an error)\r\n![image](https://github.com/dotnet/msbuild/assets/65637796/7a0493ca-624e-492e-855a-1fccc6605074)\r\n\r\n8.0\r\n![image](https://github.com/dotnet/msbuild/assets/65637796/065e4a96-a005-4e97-ad65-91597cb66182)\r\n\r\n### Analysis\r\n\r\n_No response_\r\n\r\n### Versions & Configurations\r\n\r\n_No response_",
  "state": "CLOSED",
  "createdAt": "2024-04-22T09:21:40Z",
  "updatedAt": "2024-11-06T15:48:35Z",
  "closedAt": "2024-11-06T15:48:35Z",
  "author": {
    "login": "vdanche"
  },
  "labels": [
    "bug",
    "backlog",
    "needs-design",
    "Priority:3",
    "triaged",
    "Area: Terminal Logger"
  ],
  "assignees": {
    "nodes": []
  },
  "milestone": null,
  "comments": {
    "nodes": [
      {
        "body": "This issue also repro on MacOS",
        "createdAt": "2024-04-22T09:37:04Z",
        "updatedAt": "2024-04-22T09:37:04Z",
        "author": {
          "login": "v-xiaofchen"
        }
      },
      {
        "body": "This issue also repro on Linux",
        "createdAt": "2024-04-23T02:08:45Z",
        "updatedAt": "2024-04-23T02:08:45Z",
        "author": {
          "login": "ChenhuiYuan01"
        }
      },
      {
        "body": "This is not a bug, the failed test count is 1 which is correct. The number of errors in build is 2, because xunit reports their error, and we report the error from vstest, so there are 2. \r\n\r\nThis is the same behavior as in the current execution without terminal logger: \r\n\r\n![image](https://github.com/dotnet/msbuild/assets/5735905/57876ddb-89da-44da-9682-ed23c7292a4d)\r\n\r\nThe highlighted message is **error** output that is sent by xunit.",
        "createdAt": "2024-04-23T09:55:01Z",
        "updatedAt": "2024-04-23T09:55:01Z",
        "author": {
          "login": "nohwnd"
        }
      },
      {
        "body": "I do agree it is confusing though because if there are only tests failing in the run, and no additional errors, then it is difficult to see why the counts are not matching.",
        "createdAt": "2024-04-23T09:56:52Z",
        "updatedAt": "2024-04-23T09:57:07Z",
        "author": {
          "login": "nohwnd"
        }
      }
    ]
  }
}