{
  "number": 8783,
  "title": "This is an unhandled exception in MSBuild",
  "body": "       \"D:\\sechs\\Compute-Fabric-HostAgent\\dirs.proj\" (default target) (1) ->\r\n       \"D:\\sechs\\Compute-Fabric-HostAgent\\src\\dirs.proj\" (VerifyAlteredTargetsUsed;Build target) (2) ->\r\n       \"D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\dirs.proj\" (VerifyAlteredTargetsUsed;Build target) (374) ->\r\n       \"D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\dirs.proj\" (VerifyAlteredTargetsUsed;Build target) (383) ->\r\n       \"D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj\" (VerifyAlteredTargetsUsed;Build target) (554) ->\r\n         MSBUILD : error : This is an unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE AT https://aka.ms/msbuild/unhandled. [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :     System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown. [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Go3(RegexRunner ) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Text.RegularExpressions.RegexRunner.Scan(Regex regex, String text, Int32 textbeg, Int32 textend, Int32 textstart, Int32 prevlen, Boolean quick, TimeSpan timeout) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Text.RegularExpressions.Regex.Run(Boolean quick, Int32 prevlen, String input, Int32 beginning, Int32 length, Int32 startat) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Text.RegularExpressions.Regex.Match(String input, Int32 startat) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.Shared.CanonicalError.Parse(String message) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.Utilities.TaskLoggingHelper.LogMessageFromText(String lineOfText, MessageImportance messageImportance) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.CPPTasks.VCToolTask.LogEventsFromTextOutput(String singleLine, MessageImportance messageImportance) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.Utilities.ToolTask.LogMessagesFromStandardErrorOrOutput(Queue dataQueue, ManualResetEvent dataAvailableSignal, MessageImportance messageImportance, StandardOutputOrErrorQueueType queueType) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.Utilities.ToolTask.HandleToolNotifications(Process proc) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.CPPTasks.TrackedVCToolTask.TrackerExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.Utilities.ToolTask.Execute() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.CPPTasks.VCToolTask.Execute() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.CPPTasks.TrackedVCToolTask.Execute() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.BackEnd.TaskBuilder.<InitializeAndExecuteTask>d__24.MoveNext() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteBucket>d__19.MoveNext() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__18.MoveNext() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__13.MoveNext() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.BackEnd.TargetEntry.<ProcessBucket>d__51.MoveNext() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__44.MoveNext() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__23.MoveNext() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__68.MoveNext() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n       MSBUILD : error :    at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext() [D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\LogEventHandlingTest.vcxproj]\r\n",
  "state": "OPEN",
  "createdAt": "2023-05-20T02:41:18Z",
  "updatedAt": "2024-02-21T16:27:36Z",
  "closedAt": null,
  "author": {
    "login": "Fetrovsky"
  },
  "labels": [
    "triaged"
  ],
  "assignees": {
    "nodes": []
  },
  "milestone": null,
  "comments": {
    "nodes": [
      {
        "body": "Hmm we need the string it was parsing here (one line in the output of the tool). Are you able to run the build under a debugger to get it? You will want to set /m:1 so there's only one process.\n\nSetting environment variable MSBUILDDEBUGONSTART=1 may be helpful as it pauses to allow you to attach.",
        "createdAt": "2023-05-20T12:56:07Z",
        "updatedAt": "2023-05-20T12:56:07Z",
        "author": {
          "login": "danmoseley"
        }
      },
      {
        "body": "Hello, and thank you for your response.  I have been unsuccessfully trying to reproduce.  The only difference is that I left a clean build going overnight, and now those exceptions don't happen anymore:\r\n\r\nBuild succeeded.\r\n    0 Warning(s)\r\n    0 Error(s)\r\n\r\nTime Elapsed 00:02:13.05\r\nCleaning build logs\r\nFound 0 byte file \"D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\msbuild.err\"\r\nFound 0 byte file \"D:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\\msbuild.wrn\"\r\nD:\\sechs\\Compute-Fabric-HostAgent\\src\\runtime\\test\\logeventhandling\u00bb\r\n\r\nMaybe some object or symbol files were messed up after many partial builds?",
        "createdAt": "2023-05-20T17:13:16Z",
        "updatedAt": "2023-05-20T17:13:16Z",
        "author": {
          "login": "Fetrovsky"
        }
      },
      {
        "body": "Could be, but that wouldn't explain the callstack. Hmm.",
        "createdAt": "2023-05-21T04:20:10Z",
        "updatedAt": "2023-05-21T04:20:10Z",
        "author": {
          "login": "danmoseley"
        }
      }
    ]
  }
}