{
  "number": 10258,
  "title": "Visual Studio 2022 17.10 fails to load csproj - error : The \"Target\" name is reserved, and cannot be used",
  "body": "_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-1710-fails-to-load-c/10669185)._\n\n---\n[severity:It's more difficult to complete my work] [regression] [worked-in:17.9.2]\n**Summary**\n\nAfter updating to Visual Studio 2022 Pro 17.10.0, all `csproj` projects fail to load **if an existing Windows system environment variable named `Target` is defined**. This issue was not experienced in previous versions of Visual Studio.\n\n**Environment**\n\n- Windows 11 Enterprise 23H2\n- Visual Studio Professional 2022 17.10.0\n\n**Steps to reproduce**\n\n1. Define a system environment variable named `Target` (see screenshot below)\n2. Create a .NET \"Console App\" project (in my case I used .NET 8.0 (Long Term Support) for the Framework)\n3. Close Visual Studio\n4. Navigate to the newly created project in Windows Explorer and open the `.sln`\n5. You will see a dialog \"One or more projects in the solution were not loaded correctly. Please see the Output Window for details.\" (see screenshot below)\n6. Click \"OK\"\n7. The output window will show an error similar to \"ConsoleApp1.csproj : error  : The \"Target\" name is reserved, and cannot be used.\" (see screenshot below), and the project has not been loaded.\n\\\n![vs-error-env.png](https://aka.ms/dc/image?name=B83fc29abdcfd4161bffc85e9d802cb7e638525444548501481_vs-error-env.png&tid=83fc29abdcfd4161bffc85e9d802cb7e638525444548501481)\n\n![vs-error-dialog.png](https://aka.ms/dc/image?name=B68535782b0bc4546a775d6361df4398b638525437335409163_vs-error-dialog.png&tid=68535782b0bc4546a775d6361df4398b638525437335409163)\n\n![vs-error-output.png](https://aka.ms/dc/image?name=Ba16d46ea84764215bdfa863a5bd9096c638525438318105355_vs-error-output.png&tid=a16d46ea84764215bdfa863a5bd9096c638525438318105355)\n\n**Discovered workarounds**\n\n- Delete the `Target` system environment variable, OR\n- Delete the `.vs` folder for the solution prior to opening, OR\n- After failing to open, select \"Load all projects\" on the solution from within VS -> project(s) successfully load\n\n**Additional note**\n\nIt appears that loading the solution from the Visual Studio welcome screen (recent projects) doesn't even show any errors, the project just opens in the unloaded state.\n\n**Expected behaviour**\n\n`sln / csproj` should load successfully regardless of whether a `Target` system environment variable is defined.\n\n---\n### Original Comments\n\n#### Feedback Bot on 5/29/2024, 04:18 AM: \n\n(private comment, text removed)\n\n---\n### Original Solutions\n(no solutions)",
  "state": "CLOSED",
  "createdAt": "2024-06-18T13:57:21Z",
  "updatedAt": "2024-08-09T00:09:13Z",
  "closedAt": "2024-06-20T19:58:45Z",
  "author": {
    "login": "vsfeedback"
  },
  "labels": [
    "bug",
    "Priority:1",
    "triaged"
  ],
  "assignees": {
    "nodes": [
      {
        "login": "GangWang01"
      },
      {
        "login": "rainersigwald"
      }
    ]
  },
  "milestone": null,
  "comments": {
    "nodes": [
      {
        "body": "I verified with VS 17.10.2, 17.9.7, 17.8.7. It was reproed in 17.10.2, not reproed in early versions 17.9.7, 17.8.7. It's a regression issue.\r\nIt didn't repro with msbuild.exe cli or dotnet build cli for these installed VS versions including 17.10.2.",
        "createdAt": "2024-06-19T06:27:57Z",
        "updatedAt": "2024-06-19T06:58:00Z",
        "author": {
          "login": "GangWang01"
        }
      },
      {
        "body": "Stack:\r\n\r\n```\r\n \tMicrosoft.Build.dll!Microsoft.Build.Shared.ErrorUtilities.ThrowArgument(System.Exception innerException, string resourceName, object[] args) Line 352\tC#\r\n \tMicrosoft.Build.dll!Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgument(bool condition, System.Exception innerException, string resourceName, object arg0) Line 421\tC#\r\n \tMicrosoft.Build.dll!Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgument(bool condition, string resourceName, object arg0) Line 369\tC#\r\n \tMicrosoft.Build.dll!Microsoft.Build.Execution.ProjectPropertyInstance.Create(string name, string escapedValue, bool mayBeReserved, Microsoft.Build.Construction.ElementLocation location, bool isImmutable, bool isEnvironmentProperty, Microsoft.Build.BackEnd.Logging.LoggingContext loggingContext) Line 301\tC#\r\n \tMicrosoft.Build.dll!Microsoft.Build.Execution.ProjectPropertyInstance.Create(string name, string escapedValue, bool mayBeReserved, bool isImmutable, bool isEnvironmentProperty, Microsoft.Build.BackEnd.Logging.LoggingContext loggingContext) Line 201\tC#\r\n \tMicrosoft.Build.dll!Microsoft.Build.Execution.ProjectInstance.InstantiateProjectPropertyInstance(Microsoft.Build.Evaluation.ProjectProperty property, bool isImmutable) Line 2888\tC#\r\n>\tMicrosoft.Build.dll!Microsoft.Build.Execution.ProjectInstance.CreatePropertiesSnapshot(System.Collections.Generic.ICollection<Microsoft.Build.Evaluation.ProjectProperty> properties, bool isImmutable) Line 3222\tC#\r\n \tMicrosoft.Build.dll!Microsoft.Build.Execution.ProjectInstance.ProjectInstance(Microsoft.Build.Evaluation.Project project, Microsoft.Build.Execution.ProjectInstanceSettings settings) Line 380\tC#\r\n \tMicrosoft.VisualStudio.ProjectSystem.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.ProjectSerialization.CachedProject.CreateProjectInstance(Microsoft.Build.Execution.ProjectInstanceSettings settings, Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext) Line 474\tC#\r\n \tMicrosoft.Build.dll!Microsoft.Build.Evaluation.Project.CreateProjectInstance(Microsoft.Build.Execution.ProjectInstanceSettings settings, Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext) Line 1388\tC#\r\n \tMicrosoft.Build.dll!Microsoft.Build.Evaluation.Project.CreateProjectInstance(Microsoft.Build.Execution.ProjectInstanceSettings settings) Line 1377\tC#\r\n \tMicrosoft.VisualStudio.ProjectSystem.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.Designers.ProjectSnapshotService.GenerateProjectInstance(System.IComparable configuredProjectVersion, Microsoft.VisualStudio.ProjectSystem.IProjectVersionedValue<Microsoft.VisualStudio.ProjectSystem.IProjectSnapshotInternal> latestSnapshot, Microsoft.Build.Evaluation.Project project, bool isProjectDirty) Line 298\tC#\r\n \tMicrosoft.VisualStudio.ProjectSystem.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.Designers.ProjectSnapshotService.Initialize.AnonymousMethod__1() Line 171\tC#\r\n```\r\n\r\n`InstantiateProjectPropertyInstance` is new from https://github.com/dotnet/msbuild/commit/2a789cd8bd34b92e3f508cd2eb6ecfa9343472f9#diff-40f77147ccc6867c10324ec4ddf8110ede2e43499d939b73ef83c7f5febb7a75L3001, but it's just a thin wrapper over `ProjectPropertyInstance.Create`:\r\n\r\nhttps://github.com/dotnet/msbuild/blob/9e681905e30d8298bdc138b59248825dd38eabd6/src/Build/Instance/ProjectInstance.cs#L2884-L2895\r\n\r\nSo that should be doing the same thing as before.\r\n\r\nAnd I confirm in the debugger that by the time we get to the line that throws we're still carrying the correct `mayBeReserved = true`. But the problem is that's not respected when checking against the reserved _Item_ name list:\r\n\r\nhttps://github.com/dotnet/msbuild/blob/9e681905e30d8298bdc138b59248825dd38eabd6/src/Build/Instance/ProjectPropertyInstance.cs#L295-L304\r\n\r\nHowever that code is unchanged for 6 years so is not the cause of a 17.9->17.10 regression.",
        "createdAt": "2024-06-20T19:06:11Z",
        "updatedAt": "2024-06-20T19:06:11Z",
        "author": {
          "login": "rainersigwald"
        }
      },
      {
        "body": "Building MSBuild 17.9 and plunking it into VS 17.11 repros the failure so it looks like a change in another layer. I'm going to reactivate the VS feedback and investigate further there.",
        "createdAt": "2024-06-20T19:53:36Z",
        "updatedAt": "2024-06-20T19:53:36Z",
        "author": {
          "login": "rainersigwald"
        }
      },
      {
        "body": "I have encountered this as well, see   [here](https://developercommunity.visualstudio.com/t/VS-17105-Projects-not-loading-when-ope/10718044).\r\n\r\nThe stack that I find in the logs is:\r\n\r\n`LimitedFunctionality\r\nSystem.AggregateException: Project system data flow 'ProjectEvaluationProjectCapabilitiesProvider: 61944395' closed because of an exception.\r\nThe \"Target\" name is reserved, and cannot be used.\r\n---> (Inner Exception #0) System.ArgumentException: The \"Target\" name is reserved, and cannot be used.\r\n   at Microsoft.Build.Shared.ErrorUtilities.ThrowArgument(Exception innerException, String resourceName, Object[] args)\r\n   at Microsoft.Build.Execution.ProjectPropertyInstance.Create(String name, String escapedValue, Boolean mayBeReserved, ElementLocation location, Boolean isImmutable, Boolean isEnvironmentProperty, LoggingContext loggingContext)\r\n   at Microsoft.Build.Execution.ProjectInstance.CreatePropertiesSnapshot(ICollection'1 properties, Boolean isImmutable)\r\n   at Microsoft.Build.Execution.ProjectInstance..ctor(Project project, ProjectInstanceSettings settings)\r\n   at Microsoft.VisualStudio.ProjectSystem.ProjectSerialization.CachedProject.CreateProjectInstance(ProjectInstanceSettings settings, EvaluationContext evaluationContext)\r\n   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectSnapshotService.<GenerateProjectInstanceAsync>d__38.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectSnapshotService.<>c__DisplayClass36_0.<<Initialize>b__2>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.<ExecuteWithinLockAsync>d__131'1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.VisualStudio.ProjectSystem.ProjectLockService.<ExecuteWithinLockAsync>d__131'1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectSnapshotService.<<Initialize>b__36_0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.DataflowExtensions.<>c__DisplayClass25_0'2.<<CreateSelfFilteringTransformBlock>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim'2.TransformManyBlockSlimAsync.<ProcessInputAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim'1.<ProcessInputQueueAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.ProjectDataSources.<GetLatestVersionAsync>d__40'1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.ConfiguredProjectImpl.<InitializeAsync>d__146.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<LoadConfiguredProjectImplAsync>d__262.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)\r\n   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<LoadConfiguredProjectImplAsync>d__262.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<>c__DisplayClass225_1.<<LoadConfiguredProjectAsync>b__1>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<>c__DisplayClass225_0.<<LoadConfiguredProjectAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.<LoadConfiguredProjectAsync>d__225.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<LoadConfiguredProjectAsync>d__587.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectFactory.BackgroundLoad.<LoadAndSetInitialProjectConfigurationAsync>d__42.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectFactory.BackgroundLoad.<LoadInitialConfigurationAsync>d__38.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectFactory.BackgroundLoad.Step.<<Initialize>b__14_0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectFactory.BackgroundLoad.Step.<StepAsync>d__12.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectFactory.BackgroundLoad.<RunStepsAsync>d__32.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectFactory.BackgroundLoad.<FinishLoadAsync>d__31.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectFactory.BackgroundLoad.<FinishLoadAsync>d__31.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectFactory.ParallelLoadContext.<LoadProjectAsync>d__14.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectFactory.Prefetcher.<LoadProjectAsync>d__27.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()\r\n   at Microsoft.VisualStudio.Threading.JoinableTask'1.CompleteOnCurrentThread()\r\n   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectFactory.CreateProject(String fileName, String location, String name, UInt32 flags, Guid& projectIid, IntPtr& project, Int32& canceled)\r\n   at Microsoft.VisualStudio.Shell.Flavor.FlavoredProjectFactoryBase.Microsoft.VisualStudio.Shell.Interop.IVsProjectFactory.CreateProject(String fileName, String location, String name, UInt32 flags, Guid& projectGuid, IntPtr& project, Int32& canceled)\r\n   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)\r\n   at Microsoft.VisualStudio.CommonIDE.Solutions.ProjectTypeManager.OpenProject(Guid& projectTypeGuid, String lpszCaption, String lpszFile, String lpszLocation, String lpszName, UInt32 grfCreateFlags)\r\n   at Microsoft.VisualStudio.CommonIDE.Solutions.ProjectTypeManager.<OpenProjectAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.CommonIDE.Solutions.Project.<OpenProjectUsingProjectTypeMgrAsync>d__233.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.CommonIDE.Solutions.Project.<OpenProjectAsync>d__235.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.VisualStudio.CommonIDE.Solutions.Solution.<LoadOneProjectFromFactoryAsync>d__1038.MoveNext()\r\n<--- (Inner Exception #0) \r\n\r\n`",
        "createdAt": "2024-08-09T00:05:35Z",
        "updatedAt": "2024-08-09T00:09:13Z",
        "author": {
          "login": "bbmmcodegirl"
        }
      }
    ]
  }
}