{
  "number": 5508,
  "title": "ToolTasks Can Log MSB4181 When Cancelled",
  "body": "### Steps to reproduce\r\n\r\nAssume there is a tool named \"sleep\" in the path. Build this project, then hit Ctrl-C.\r\n```xml\r\n<Project>\r\n\r\n  <Target Name=\"t\">\r\n    <Exec Command=\"sleep 1000000\"/>\r\n  </Target>\r\n\r\n</Project>\r\n```\r\n\r\n### Actual behavior\r\n```\r\nC:\\proj>dotnet msbuild test.proj\r\nMicrosoft (R) Build Engine version 16.7.0-preview-20330-08+96403c598 for .NET\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nAttempting to cancel the build...\r\nC:\\proj\\test.proj(4,5): warning MSB5021: Terminating the task executable \"cmd\" and its child processes because the build was canceled.\r\nC:\\proj\\test.proj(4,5): error MSB4181: The \"Exec\" task returned false but did not log an error.\r\n```\r\n\r\n\r\n### Expected behavior\r\n\r\nIf the task was canceled, suppress MSB4181.\r\n\r\nMSB4181 is a grumble that the task does not follow the contract of \"return false if an only if you logged an error\". But in the case of cancelation, this error is useless for the user, who just hit Ctrl-C, and for the task author, who returned immediately exactly as the engine required them to. We don't want task authors to start logging bogus errors on cancelation. Just continue and fail the build with `MSB4188: Build was canceled`  in the normal way.\r\n\r\n### Environment data\r\n```\r\nC:\\proj>dotnet msbuild /version\r\nMicrosoft (R) Build Engine version 16.7.0-preview-20330-08+96403c598 for .NET\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\n16.7.0.33008\r\n```\r\n",
  "state": "CLOSED",
  "createdAt": "2020-07-12T05:36:26Z",
  "updatedAt": "2024-02-21T17:03:04Z",
  "closedAt": "2021-10-31T17:39:47Z",
  "author": {
    "login": "danmoseley"
  },
  "labels": [
    "Area: Debuggability",
    "Area: Tasks",
    "For consideration",
    "triaged"
  ],
  "assignees": {
    "nodes": [
      {
        "login": "benvillalobos"
      }
    ]
  },
  "milestone": {
    "title": "VS 17.1"
  },
  "comments": {
    "nodes": [
      {
        "body": "Someone else brought this up with me but I can't find it now. I agree.",
        "createdAt": "2020-07-15T16:14:55Z",
        "updatedAt": "2020-07-15T16:14:55Z",
        "author": {
          "login": "rainersigwald"
        }
      },
      {
        "body": "The `Copy` task does this as well when `ContineOnError` is set to `true`\r\n\r\n```xml\r\n<Project>\r\n  <Target Name=\"Build\">\r\n    <ItemGroup>\r\n      <SourceFiles Include=\"Foo\" />\r\n    </ItemGroup>\r\n    <Copy SourceFiles=\"@(SourceFiles)\"\r\n          DestinationFolder=\"$(MSBuildBinPath)\"\r\n          ContinueOnError=\"true\"\r\n          Retries=\"0\" />\r\n  </Target>\r\n</Project>\r\n```\r\n\r\n```\r\nD:\\>msbuild D:\\Stuff\\MSB4181.proj /clp:v=m;summary;forcenoalign\r\nMicrosoft (R) Build Engine version 16.8.0-preview-20411-05+9a32a8063 for .NET Framework\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nD:\\Stuff\\MSB4181.proj(6,5): warning MSB3021: Unable to copy file \"Foo\" to \"C:\\Program Files (x86)\\Visual Studio 2019 Preview\\MSBuild\\Current\\Bin\\Foo\". Access to the path 'C:\\Program Files (x86)\\Visual Studio 2019 Preview\\MSBuild\\Current\\Bin\\Foo' is denied.\r\nD:\\Stuff\\MSB4181.proj(6,5): warning MSB4181: The \"Copy\" task returned false but did not log an error.\r\n\r\nBuild succeeded.\r\n\r\nD:\\Stuff\\MSB4181.proj(6,5): warning MSB3021: Unable to copy file \"Foo\" to \"C:\\Program Files (x86)\\Visual Studio 2019 Preview\\MSBuild\\Current\\Bin\\Foo\". Access to the path 'C:\\Program Files (x86)\\Visual Studio 2019 Preview\\MSBuild\\Current\\Bin\\Foo' is denied.\r\nD:\\Stuff\\MSB4181.proj(6,5): warning MSB4181: The \"Copy\" task returned false but did not log an error.\r\n    2 Warning(s)\r\n    0 Error(s)\r\n\r\nTime Elapsed 00:00:00.38\r\n```\r\n\r\nWhen ContinueOnError is set, I wouldn't expect to get this warning as errors were technically mutated to a warning.  When I saw this, a user had suppressed `MSB3021` but now their build fails because of the new warning.",
        "createdAt": "2020-08-12T17:28:24Z",
        "updatedAt": "2020-08-12T17:28:24Z",
        "author": {
          "login": "jeffkl"
        }
      },
      {
        "body": "Poking at this a little bit with `msbuild msbuild.dev.slnf` and cancelling at random times, I hit the same thing with `Csc`. Whatever the fix is should work with any task that's cancelled.\r\n\r\nMSB4188 is never emitted, right?",
        "createdAt": "2021-09-15T22:38:55Z",
        "updatedAt": "2021-09-15T22:38:55Z",
        "author": {
          "login": "benvillalobos"
        }
      },
      {
        "body": "@danmoseley I don't repro this issue. This may have been fixed with our various taskhost HasLoggedErrors PR's. Closing this in favor of https://github.com/dotnet/msbuild/issues/5912 which I think is a larger issue with tooltasks.\r\n\r\nEDIT: It occurred to me the other issue is specific to LC (not necessarily cancelling), so I'll stick with this as the canonical issue that ANY tooltask that is cancelled can log this error.",
        "createdAt": "2021-10-14T21:03:31Z",
        "updatedAt": "2021-10-14T21:07:29Z",
        "author": {
          "login": "benvillalobos"
        }
      },
      {
        "body": "Yes that seems different. I do still see this from time to time and we keep relatively up to date with SDK builds ",
        "createdAt": "2021-10-14T21:13:38Z",
        "updatedAt": "2021-10-14T21:13:38Z",
        "author": {
          "login": "danmoseley"
        }
      }
    ]
  }
}