{
  "number": 853,
  "title": "MSBuildLastTaskResult not set to false after an error executing msbuild with ContinueOnError=\"ErrorAndContinue\" ",
  "body": "When we are running tests in CoreFx and a test Fail, MSBuild task is not setting the property `MSBuildLastTaskResult` to false, so the return exit code is 0.\n\nAfter some tests, I got the following output from msbuild:\n\n```\nD:\\mariariCoreFx\\Tools\\tests.targets(256,5): warning MSB3073: The command \"D:\\mariariCoreFx\\bin/tests/AnyOS.AnyCPU.Debug/Microsoft.CSharp.Tests/netcoreapp1.0/RunTests.cmd D:\\mariariCoreFx\\packages/\" exited with code 1. [D:\\mariariCoreFx\\src\\Microsoft.CSharp\\tests\\Microsoft.CSharp.Tests.csproj]\nThe previous error was converted to a warning because the task was called with ContinueOnError=true. (TaskId:186)\nOutput Property: TestRunExitCode=1 (TaskId:186)\nBuild continuing because \"ContinueOnError\" on the task \"Exec\" is set to \"true\". (TaskId:186)\nDone executing task \"Exec\" -- FAILED. (TaskId:186)\nTask \"Delete\" skipped, due to false condition; ('$(DeletePerfDataFile)' == 'true') was evaluated as ('' == 'true').\nUsing \"Error\" task from assembly \"Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\".\nTask \"Error\" (TaskId:187)\nTask Parameter:Text=One or more tests failed while running tests from 'Microsoft.CSharp.Tests' please check log for details! (TaskId:187)\nD:\\mariariCoreFx\\Tools\\tests.targets(265,5): error : One or more tests failed while running tests from 'Microsoft.CSharp.Tests' please check log for details! [D:\\mariariCoreFx\\src\\Microsoft.CSharp\\tests\\Microsoft.CSharp.Tests.csproj]\nDone executing task \"Error\" -- FAILED. (TaskId:187)\nDone Building Project \"D:\\mariariCoreFx\\src\\Microsoft.CSharp\\tests\\Microsoft.CSharp.Tests.csproj\" (PrepareForRun;Test target(s)) -- FAILED.\nDone executing task \"MSBuild\". (TaskId:157)\nTask \"Error\" skipped, due to false condition; ('$(MSBuildLastTaskResult)'=='false') was evaluated as ('true'=='false').\nDone building target \"TestAllProjects\" in project \"Microsoft.CSharp.Tests.builds\".: (TargetId:236)\nTarget \"Build: (TargetId:237)\" in file \"D:\\mariariCoreFx\\dir.traversal.targets\" from project \"D:\\mariariCoreFx\\src\\Microsoft.CSharp\\tests\\Microsoft.CSharp.Tests.builds\" (entry point):\nDone building target \"Build\" in project \"Microsoft.CSharp.Tests.builds\".: (TargetId:237)\nDone Building Project \"D:\\mariariCoreFx\\src\\Microsoft.CSharp\\tests\\Microsoft.CSharp.Tests.builds\" (Build target(s)).\nDone executing task \"MSBuild\". (TaskId:5)\nTask \"Error\" skipped, due to false condition; ('$(MSBuildLastTaskResult)'=='false') was evaluated as ('true'=='false').\n```\n\nThe call comes from [dir.traversal.targets](https://github.com/dotnet/corefx/blob/295820fbdd6c3a596a99e2268c0cbec66692694f/dir.traversal.targets#L175)\n\n```\n<MSBuild Targets=\"PrepareForRun;Test\"\n             Projects=\"@(ProjectsToTest)\"\n             Condition=\"'$(SerializeProjects)'!='true'\"\n             Properties=\"DefaultBuildAllTarget=$(DefaultBuildAllTarget);BuildAllProjects=true\"\n             BuildInParallel=\"true\"\n             ContinueOnError=\"ErrorAndContinue\" />\n\n<!-- Given we ErrorAndContinue we need to propagate the error if the overall task failed -->\n<Error Condition=\"'$(MSBuildLastTaskResult)'=='false'\" />\n```\n",
  "state": "CLOSED",
  "createdAt": "2016-08-02T17:31:12Z",
  "updatedAt": "2024-02-21T17:26:49Z",
  "closedAt": "2019-10-21T20:35:05Z",
  "author": {
    "login": "maririos"
  },
  "labels": [
    "triaged"
  ],
  "assignees": {
    "nodes": []
  },
  "milestone": null,
  "comments": {
    "nodes": [
      {
        "body": "cc: @rainersigwald \n",
        "createdAt": "2016-08-02T17:31:46Z",
        "updatedAt": "2016-08-02T17:31:46Z",
        "author": {
          "login": "maririos"
        }
      },
      {
        "body": "What MSBuild package version are you using, @maririos? And what's the version of `System.Diagnostics.Process.dll`?\n",
        "createdAt": "2016-08-02T18:03:49Z",
        "updatedAt": "2016-08-02T18:03:49Z",
        "author": {
          "login": "rainersigwald"
        }
      },
      {
        "body": "On windows I'm using the msbuild that is in the box and in non-windows I'm using msbuild 14.1.0.0.\nThe version of System.Diagnostic.Process.dll is 4.6.24027.00 from the Microsoft.NETCore.App 1.0.0-rc3-002733\n",
        "createdAt": "2016-08-02T20:50:31Z",
        "updatedAt": "2016-08-02T20:50:31Z",
        "author": {
          "login": "maririos"
        }
      },
      {
        "body": "I kept looking at the error, and in windows, when using the local msbuild, the error code only fails when we pass the /m option.\ni.e\n`D:\\mariariCoreFx\\Tools\\msbuild.cmd   /nodeReuse:false /nologo /maxcpucount /verbosity:minimal src/tests.builds` exit code =0\n`D:\\mariariCoreFx\\Tools\\msbuild.cmd   /nodeReuse:false /nologo /verbosity:minimal src/tests.builds` exit code =1\n\nIt may be related to how we are defining our targets. I'll keep looking.\n\nFor the non-windows runs, it seems related to something with Process.Start, as when I call a tool that uses Process.Start(msbuild, args) the exit code is 0 but when I directly call msbuild in the terminal, the exit code is 1.\n",
        "createdAt": "2016-08-02T22:27:49Z",
        "updatedAt": "2016-08-02T22:27:49Z",
        "author": {
          "login": "maririos"
        }
      },
      {
        "body": "Team triage: closing due to lack of repro information.",
        "createdAt": "2019-10-21T20:35:05Z",
        "updatedAt": "2019-10-21T20:35:05Z",
        "author": {
          "login": "rainersigwald"
        }
      }
    ]
  }
}